{{- if .Values.clusterrolebindings.enabled }}
{{- range $item := .Values.clusterrolebindings.data}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $item.name }}-{{ $.Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $item.role }}-{{ $.Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $item.serviceAccount }}-{{ $.Values.namespace }}
    namespace: {{ $.Values.namespace }}

---
{{- end}}
{{- end}}