{{- range $item := .Values.secrets}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $item.name }}
type: Opaque
stringData:
  {{- range $key, $value := $item.data }}
  {{ $key }}: {{ tpl $value $ | quote }}

  {{- end }}
---

{{- end }}