apiVersion: batch/v1
kind: CronJob
metadata:
  name: stock-discovery-cronjob
spec:
  schedule: "30 1 * * *" # Runs at 7:00 AM everyday
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: discovery-engine
            image: kingaiva/signal-engine:stable
            env:
              - name: STOCKFLOW_CONTROLLER
                valueFrom:
                  configMapKeyRef:
                    name: service-urls
                    key: STOCKFLOW_CONTROLLER
              - name: SF_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: api-credentials
                    key: api-key
              - name: EQUITY_CSV_PATH
                value: "/home/ubuntu/app/EQUITY_L.csv"
            command: ["/bin/bash", "-c", "python3 /home/ubuntu/app/discovery-engine.py"]
            volumeMounts:
              - name: cronjob-config-volume
                mountPath: /home/ubuntu/app/discovery-engine.py
                subPath: discovery-engine.py
              - name: cronjob-config-volume
                mountPath: /home/ubuntu/app/EQUITY_L.csv
                subPath: EQUITY_L.csv
          restartPolicy: OnFailure
          volumes:
            - name: cronjob-config-volume
              configMap:
                name: cronjob-config
