apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 7200
      template:
        spec:
          containers:
          - name: health-check
            image: kingaiva/signal-engine:dev
            env:
              - name: SMTP_HOST
                valueFrom:
                  secretKeyRef:
                    name: smtp-credentials
                    key: smtp-host
              - name: SMTP_PORT
                valueFrom:
                  secretKeyRef:
                    name: smtp-credentials
                    key: smtp-port
              - name: SMTP_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: smtp-credentials
                    key: smtp-password
              - name: API_KEY
                valueFrom:
                  secretKeyRef:
                    name: api-credentials
                    key: api-key
              - name: DEPLOY_TYPE
                value: "__DEPLOY_TYPE__"
              - name: SIGNAL_ENGINE
                valueFrom: 
                  configMapKeyRef:
                    name: service-urls
                    key: SIGNAL_ENGINE
              - name: MARKET_INTEL_ENGINE
                valueFrom: 
                  configMapKeyRef:
                    name: service-urls
                    key: MARKET_INTEL_ENGINE
              - name: EVENT_DISPATCHER
                valueFrom: 
                  configMapKeyRef:
                    name: service-urls
                    key: EVENT_DISPATCHER
              - name: KUBESNAP
                valueFrom: 
                  configMapKeyRef:
                    name: service-urls
                    key: KUBESNAP
              - name: STOCKFLOW_CONTROLLER
                valueFrom: 
                  configMapKeyRef:
                    name: service-urls
                    key: STOCKFLOW_CONTROLLER
            command: ["/bin/bash", "-c", "python3 /home/ubuntu/app/healthcheck-execution.py"]
            volumeMounts:
              - name: cronjob-config-volume
                mountPath: /home/ubuntu/app/healthcheck-execution.py
                subPath: healthcheck-execution.py
          restartPolicy: OnFailure
          volumes:
            - name: cronjob-config-volume
              configMap:
                name: cronjob-config