apiVersion: batch/v1
kind: CronJob
metadata:
  name: signal-check-cronjob
spec:
  schedule: "30 2 * * 1,2,3,4,5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: signal-check
            image: kingaiva/signal-engine:dev
            env:
              - name: STOCKFLOW_CONTROLLER
                valueFrom:
                  configMapKeyRef:
                    name: service-urls  
                    key: STOCKFLOW_CONTROLLER
              - name: SIGNAL_ENGINE
                valueFrom:
                  configMapKeyRef:
                    name: service-urls
                    key: SIGNAL_ENGINE
              - name: MARKET_INTEL_ENGINE
                valueFrom:
                  configMapKeyRef:
                    name: service-urls
                    key: MARKET_INTEL_ENGINE
              - name: EVENT_DISPATCHER
                valueFrom:
                  configMapKeyRef:
                    name: service-urls
                    key: EVENT_DISPATCHER
              - name: SMTP_HOST
                valueFrom:
                  secretKeyRef:
                    name: smtp-credentials
                    key: smtp-host
              - name: SMTP_PORT
                valueFrom:
                  secretKeyRef:
                    name: smtp-credentials
                    key: smtp-port
              - name: SMTP_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: smtp-credentials
                    key: smtp-password
              - name: SF_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: api-credentials
                    key: api-key
            command: ["/bin/bash", "-c", "python3 /home/ubuntu/app/cronjob-execution.py"]
            volumeMounts:
              - name: cronjob-config-volume
                mountPath: /home/ubuntu/app/cronjob-execution.py
                subPath: cronjob-execution.py
              - name: cronjob-config-volume
                mountPath: /home/ubuntu/app/EQUITY_L.csv
                subPath: EQUITY_L.csv
              - name: cronjob-config-volume
                mountPath: /home/ubuntu/app/smtp_email_trigger.py
                subPath: smtp_email_trigger.py
              - name: cronjob-config-volume
                mountPath: /home/ubuntu/app/market_analysis_prompt.txt
                subPath: market_analysis_prompt.txt
              - name: cronjob-config-volume
                mountPath: /home/ubuntu/app/email-template.html
                subPath: email-template.html
              - name: cronjob-config-volume
                mountPath: /home/ubuntu/app/top_500_nse_tickers.py
                subPath: top_500_nse_tickers.py
              - name: top-stocks-volume
                mountPath: /app/data
          restartPolicy: OnFailure
          volumes:
            - name: cronjob-config-volume
              configMap:
                name: cronjob-config
            - name: top-stocks-volume
              configMap:
                name: top-stocks-cm
                optional: true
