apiVersion: apps/v1
kind: Deployment
metadata:
    name: stockflow-controller
    labels:
      app: stockflow-controller
spec:
    replicas: 1
    selector:
      matchLabels:
        app: stockflow-controller
    template:
      metadata:
        labels:
          app: stockflow-controller
      spec:
        serviceAccountName: controller-svc-acc
        containers:
        - name: stockflow-controller
          image: kingaiva/stockflow-controller:dev
          env:
            - name: PORT
              value: "9000"
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: sc-port