{{- range $item := .Values.configmaps }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $item.name }}
data:
{{- if $item.files }}
  {{- range $file_item := $item.files }}
  {{ $file_item.name }}: |
{{ $.Files.Get (printf "files/%s" $file_item.name) | indent 4 }}
  {{- end }}
{{- else }}
  {{- range $key, $value := $item.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

---
{{- end }}