{{- range $item := .Values.services}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $item.name }}
spec:
  type : ClusterIP
  selector:
    app: {{ $item.name }}
  ports:
  - name: {{ $item.portName }}
    protocol: TCP
    port: {{ $item.port }}
    targetPort: {{ $item.targetPort }}

---
{{- end}}