---
name: test-deployment
on:
  workflow_call:
jobs:
  test:
   name: test-deployment
   runs-on: self-hosted
   steps:
   - name: Checkout
     uses: actions/checkout@v2
 
   - name: test-services
     run: |
       bash test_deploy.sh
